/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wos_play_rootdir_model_monitor_soexcute_RunJniHelper */

#ifndef _Included_com_wos_play_rootdir_model_monitor_soexcute_RunJniHelper
#define _Included_com_wos_play_rootdir_model_monitor_soexcute_RunJniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wos_play_rootdir_model_monitor_soexcute_RunJniHelper
 * Method:    startMservice
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_wos_play_rootdir_model_1monitor_soexcute_RunJniHelper_startMservice
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_wos_play_rootdir_model_monitor_soexcute_RunJniHelper
 * Method:    stopMservice
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wos_play_rootdir_model_1monitor_soexcute_RunJniHelper_stopMservice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wos_play_rootdir_model_monitor_soexcute_RunJniHelper
 * Method:    liveAll
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wos_play_rootdir_model_1monitor_soexcute_RunJniHelper_liveAll
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wos_play_rootdir_model_monitor_soexcute_RunJniHelper
 * Method:    killAll
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wos_play_rootdir_model_1monitor_soexcute_RunJniHelper_killAll
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
